import type { CommandType } from '../types/command'

export const AVAILABLE_COMMANDS: CommandType[] = [
  'start',
  'restart',
  'shutdown',
  'help',
  'status',
  'clear',
  'cls',
  'containment',
  'scp-list',
  'info',
  'protocol',
  'emergency',
  'logout',
  'version',
  'about',
  'search',
  'network',
  'performance',
  'check',
  'ls',
  'cd',
  'pwd',
  'mkdir',
  'rm',
  'cat',
  'echo',
  'touch',
  'cp',
  'mv',
  'uname',
  'df',
  'free',
  'uptime',
  'find',
  'grep',
  'chmod',
  'penetration',
  'chown'
]

export const COMMAND_DESCRIPTIONS: Record<CommandType, string> = {
  start: 'Start the system (first-time initialization)',
  restart: 'Restart the system',
  shutdown: 'Shutdown the system',
  help: 'Display available commands',
  status: 'Show system status and containment statistics',
  clear: 'Clear terminal screen',
  cls: 'Clear terminal screen',
  containment: 'Display containment protocol classification',
  'scp-list': 'List known SCP objects',
  info: 'Query detailed information about specific SCP (supports CN branch with CN- prefix)',
  protocol: 'Display security protocols and task forces',
  emergency: 'Display emergency contact information',
  logout: 'Secure logout',
  version: 'Display system version',
  about: 'Display system information',
  search: 'Search SCP database (supports Chinese keywords)',
  network: 'Test network connection to Foundation Wiki',
  performance: 'Open Performance Monitor Dashboard',
  check: 'Run system security check',
  ls: 'List directory contents',
  cd: 'Change current directory',
  pwd: 'Print current working directory',
  mkdir: 'Create directory',
  rm: 'Remove file or directory',
  cat: 'Display file content',
  echo: 'Print text or write to file',
  touch: 'Create empty file',
  cp: 'Copy file or directory',
  mv: 'Move or rename file or directory',
  uname: 'Display system information',
  df: 'Display disk space usage',
  free: 'Display memory usage',
  uptime: 'Display system uptime',
  find: 'Find files',
  grep: 'Search file content',
  chmod: 'Change file permissions',
  penetration: 'Launch virtual penetration testing session (SCP Foundation authorized)',
  chown: 'Change file owner'
}

export const COMMAND_USAGE: Record<CommandType, string> = {
  start: 'start',
  restart: 'restart',
  shutdown: 'shutdown now',
  help: 'help',
  status: 'status',
  clear: 'clear',
  cls: 'cls',
  containment: 'containment',
  'scp-list': 'scp-list',
  info: 'info <number>|info CN-<number>',
  protocol: 'protocol',
  emergency: 'emergency',
  logout: 'logout',
  version: 'version',
  about: 'about',
  search: 'search <keyword>',
  network: 'network',
  performance: 'performance',
  check: 'check',
  ls: 'ls [path]',
  cd: 'cd <path>',
  pwd: 'pwd',
  mkdir: 'mkdir <directory>',
  rm: 'rm <file|directory>',
  cat: 'cat <file>',
  echo: 'echo <text> [> <file>]',
  touch: 'touch <file>',
  cp: 'cp <source> <destination>',
  mv: 'mv <source> <destination>',
  uname: 'uname [-a]',
  df: 'df',
  free: 'free',
  uptime: 'uptime',
  find: 'find <path> -name <pattern>',
  grep: 'grep <pattern> <file>',
  chmod: 'chmod <permissions> <file>',
  penetration: 'penetration',
  chown: 'chown <owner>:<group> <file>'
}